name: Publish pkg-pr
on:
  push:
    branches:
      - main
    tags:
      - '!**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Publish lism-core
        if: contains(github.event.head_commit.message, '[core]')
        run: |
          pnpm build:core
          pnpx pkg-pr-new publish './packages/lism-core'

      - name: Publish lism-astro
        if: contains(github.event.head_commit.message, '[astro]')
        run: pnpx pkg-pr-new publish './packages/lism-astro'

      - name: Publish lism-next
        if: contains(github.event.head_commit.message, '[next]')
        run: pnpx pkg-pr-new publish './packages/lism-next'
