name: Publish pkg-pr
on:
  push:
    branches:
      - main
    tags:
      - '!**'

jobs:
  build:
    # if: contains(github.event.head_commit.message, '[')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Publish lism-core
        # if: contains(github.event.head_commit.message, '[core]')
        run: |
          pnpm install
          pnpm build:core
          pnpx pkg-pr-new publish './packages/lism-core' || true

      - name: Publish lism-astro
        # if: contains(github.event.head_commit.message, '[astro]')
        run: pnpx pkg-pr-new publish './packages/lism-astro' || true

      - name: Publish lism-next
        # if: contains(github.event.head_commit.message, '[next]')
        run: pnpx pkg-pr-new publish './packages/lism-next' || true
